version: v1.0.0

baseGoContainer: &baseGoContainer
  name: go
  image: quay.io/deis/lightweight-docker-go:v0.6.0
  sourceMountPath: /go/src/github.com/deislabs/porter
  workingDirectory: /go/src/github.com/deislabs/porter
  tty: true

targets:

################################################################################
# Utility targets                                                              #
################################################################################

  dep:
    containers:
    - <<: *baseGoContainer
      command: dep ensure -v

################################################################################
# Test targets                                                                 #
################################################################################

  verify-vendored-code:
    containers:
    - <<: *baseGoContainer
      command: dep check

  test-unit:
    containers:
    - <<: *baseGoContainer
      command: go test -timeout 30s -race -coverprofile=coverage.txt -covermode=atomic ./cmd/... ./pkg/...

  lint:
    containers:
    - <<: *baseGoContainer
      command: golangci-lint run ./cmd/... ./pkg/...

################################################################################
# Build / publish targets                                                      #
################################################################################

  clean:
    containers:
    - <<: *baseGoContainer
      command: rm -rf bin/

  build-porter-linux-amd64:
    containers:
    - <<: *baseGoContainer
      environment:
      - CGO_ENABLED=0
      command: scripts/build-porter.sh linux amd64

  build-porter-darwin-amd64:
    containers:
    - <<: *baseGoContainer
      environment:
      - CGO_ENABLED=0
      command: scripts/build-porter.sh darwin amd64

  build-porter-windows-amd64:
    containers:
    - <<: *baseGoContainer
      environment:
      - CGO_ENABLED=0
      command: scripts/build-porter.sh windows amd64

################################################################################
# Pipelines                                                                    #
################################################################################

pipelines:

################################################################################
# Utility pipelines                                                            #
################################################################################

  build:
    stages:
    - targets:

################################################################################
# CI pipelines                                                                 #
################################################################################

  test:
    criteria:
      branches:
        ignore:
        - master
    stages:
    - targets:
      - env
    - targets:
      - lint
      - verify-vendored-code
      - test-unit
    - targets:
      - build-porter-linux-amd64
      - build-porter-darwin-amd64
      - build-porter-windows-amd64

  master:
    criteria:
      branches:
        only:
        - master
    stages:
    - targets:
      - env
    - targets:
      - lint
      - verify-vendored-code
      - test-unit
    - targets:
      - build-porter-linux-amd64
      - build-porter-darwin-amd64
      - build-porter-windows-amd64

################################################################################
# Release pipeline                                                             #
################################################################################

  release:
    criteria:
      tags:
        only:
        - /v[0-9]+(\.[0-9]+)*(\-.+)?/
    stages:
    - targets:
      - env
    - targets:
      - build-porter-linux-amd64
      - build-porter-darwin-amd64
      - build-porter-windows-amd64
    - targets:
      # TODO: publish
